"""Loading the hand-labelled ground truth a fidelity score is measured against.

``tests/fixtures/ground_truth.json`` is generated by ``scripts/make_fixtures.py``
alongside the corpus and is the only thing in this project that knows what a
correct conversion looks like. It is data, not code: this module reads it and
does not interpret it, and every judgement about what a field *means* lives in
:mod:`tokenmill.fidelity.scorer`.

The corpus is a development artefact rather than packaged data — it ships in the
sdist and not in the wheel — so the loader takes a path and does not guess. A
caller that wants the repository's own corpus passes its path; the CLI resolves
a sensible default and says which file it used.
"""

from __future__ import annotations

import json
from collections.abc import Mapping
from pathlib import Path
from typing import Any, Final

from tokenmill.core.errors import ConfigError

__all__ = [
    "GROUND_TRUTH_FILENAME",
    "load_ground_truth",
    "resolve_fixture",
]

#: The manifest's filename, wherever the corpus lives.
GROUND_TRUTH_FILENAME: Final = "ground_truth.json"


def load_ground_truth(path: Path) -> Mapping[str, Mapping[str, Any]]:
    """Read a ground-truth manifest.

    Args:
        path: The manifest file, or the directory containing it.

    Returns:
        The per-fixture mapping, keyed by fixture name.

    Raises:
        ConfigError: If the file is missing, is not JSON, or does not have the
            shape ``make_fixtures.py`` writes. Each carries a hint naming the
            command that regenerates it, because a corrupt manifest is fixed by
            regenerating rather than by editing — the corpus is generated and
            hand-editing it is what ``CONTRIBUTING.md`` forbids.
    """
    manifest_path = path / GROUND_TRUTH_FILENAME if path.is_dir() else path
    try:
        raw = manifest_path.read_text(encoding="utf-8")
    except OSError as exc:
        msg = f"could not read ground truth from {manifest_path}"
        raise ConfigError(msg, hint="generate it with `python scripts/make_fixtures.py`") from exc

    try:
        manifest = json.loads(raw)
    except json.JSONDecodeError as exc:
        msg = f"{manifest_path} is not valid JSON"
        raise ConfigError(msg, hint="regenerate it with `python scripts/make_fixtures.py`") from exc

    fixtures = manifest.get("fixtures") if isinstance(manifest, dict) else None
    if not isinstance(fixtures, dict):
        msg = f"{manifest_path} has no 'fixtures' object"
        raise ConfigError(msg, hint="regenerate it with `python scripts/make_fixtures.py`")
    return {name: entry for name, entry in fixtures.items() if isinstance(entry, dict)}


def resolve_fixture(
    fixtures: Mapping[str, Mapping[str, Any]], name: str
) -> tuple[str, Mapping[str, Any]]:
    """Find one fixture's ground truth, forgiving the obvious near-misses.

    A user who converted ``tests/fixtures/tables.pdf`` will type that path, or
    ``tables.pdf``, and both should work. A directory fixture is keyed with a
    trailing slash in the manifest (``sample_repo/``) and nobody types that.

    Args:
        fixtures: The loaded per-fixture mapping.
        name: What the user asked for: a fixture name, or a path ending in one.

    Returns:
        The canonical fixture name and its ground truth.

    Raises:
        ConfigError: If no fixture matches, listing what is available. Guessing
            harder would mean scoring a document against the wrong answer key,
            which produces a plausible number that means nothing.
    """
    basename = Path(name).name or name.rstrip("/").rsplit("/", maxsplit=1)[-1]
    for candidate in (name, basename, f"{name}/", f"{basename}/"):
        if candidate in fixtures:
            return candidate, fixtures[candidate]

    known = ", ".join(sorted(fixtures)) or "none"
    msg = f"no ground truth for {name!r}"
    raise ConfigError(msg, hint=f"known fixtures: {known}")
