"""Regenerate `TABLES.md` from the committed benchmark results.

    uv run python docs/article/make_tables.py

Every table in the article pack is produced by this script from
`benchmarks/results/<run>/results.json`, so a table cannot drift away from the
data it claims to come from. Retyping a number into prose is how a benchmark
becomes marketing, and this project has already caught itself doing a smaller
version of it twice.

The tables are written for pasting into an article, which is why they carry
their unit and their fidelity column even where that makes them wider than a
table drawn for looks. A reduction figure without a fidelity figure beside it is
not a result.
"""

from __future__ import annotations

import argparse
import json
import statistics
from collections.abc import Sequence
from pathlib import Path
from typing import Any, Final

__all__ = ["main", "render"]

#: The run these tables describe.
DEFAULT_RUN: Final = Path(__file__).resolve().parents[2] / "benchmarks" / "results" / "2026-08-27"

#: Where to write.
DEFAULT_OUT: Final = Path(__file__).resolve().parent / "TABLES.md"

#: The three HTML fixtures, in the order that tells the story: a page with
#: little boilerplate, a page that is mostly boilerplate, and a page whose
#: content is not in the response at all.
_HTML_ORDER: Final = ("article.html", "boilerplate.html", "jsrendered.html")

#: The scorable PDFs. `scanned.pdf` is deliberately not here; it has its own
#: table, because four of its cells succeed and produce nothing.
_PDF_ORDER: Final = ("simple.pdf", "tables.pdf", "twocolumn.pdf")


def _rows(run: Path) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    """Load a run.

    Args:
        run: The results directory.

    Returns:
        Its cells and its manifest.
    """
    payload = json.loads((run / "results.json").read_text(encoding="utf-8"))
    return payload["results"], payload["manifest"]


def _median_ms(row: dict[str, Any]) -> float | None:
    """The middle timing of a cell.

    Args:
        row: The cell.

    Returns:
        The median in milliseconds, or ``None`` when nothing was timed.
    """
    durations = row.get("durations_ms") or []
    return statistics.median(durations) if durations else None


def _fmt_fidelity(row: dict[str, Any]) -> str:
    """Render a fidelity score with its component count.

    Args:
        row: The cell.

    Returns:
        ``"0.848 (3)"``, or ``"n/a"`` where nothing could be scored. Never a
        bare number: a 1.000 from one component and a 1.000 from four are
        different claims.
    """
    if row["fidelity"] is None:
        return "n/a"
    return f"{row['fidelity']:.3f} ({row['fidelity_scored']})"


def _fmt_change(row: dict[str, Any]) -> str:
    """Render a reduction with a real minus sign and the right direction.

    Args:
        row: The cell.

    Returns:
        ``"-77.1%"`` for a saving, ``"+9.5%"`` for growth, ``"n/a"`` where there
        is no comparable before-count. The sign convention is the one this
        project got wrong in Phase 1 and again in Phase 10: a saving is
        negative, because the number went down.
    """
    if row.get("reduction") is None or row.get("tokens_before") is None:
        return "n/a"
    return f"{-row['reduction']:+.1%}".replace("-", "−")


def render(rows: Sequence[dict[str, Any]], manifest: dict[str, Any]) -> str:
    """Build the whole file.

    Args:
        rows: Every cell of the run.
        manifest: Its provenance.

    Returns:
        The markdown.
    """
    by_key = {(r["fixture"], r["backend"]): r for r in rows}
    out: list[str] = []
    add = out.append

    add("# Tables, ready to paste")
    add("")
    add("**Generated by `docs/article/make_tables.py`. Do not edit by hand** —")
    add("regenerate it, so a number here cannot drift from the run it came from.")
    add("")
    add(f"Source: `benchmarks/results/{DEFAULT_RUN.name}/`, commit")
    add(f"`{manifest['git_commit'][:7]}`, corpus digest `{manifest['corpus_digest']}`,")
    add(f"{manifest['platform']}, Python {manifest['python']},")
    add(f"{manifest['cpu_count']} cores, N={manifest['repeats']}.")
    add("")
    add("> **Every count in this file is UTF-8 bytes, not model tokens.** The")
    add("> environment these were measured in cannot reach a tokenizer vocabulary.")
    add("> A byte figure is a lower bound on cost, an upper bound on saving, and")
    add("> not a reliable ordering — on this project's own tabular data the two")
    add("> units disagreed by 24 points and did not rank five serialisation")
    add("> formats in the same order. If you quote these as token savings you are")
    add("> saying something we did not measure.")
    add("")
    add("Fidelity is written `score (components)`. A 1.000 from one component")
    add("and a 1.000 from four are different claims.")
    add("")

    # --- Table 1: web extraction, the whole point --------------------------
    add("## Table 1 — Web extraction: the saving is the boilerplate")
    add("")
    add("| Page | Backend | Before | After | Change | Fidelity |")
    add("|---|---|---|---|---|---|")
    for fixture in _HTML_ORDER:
        for row in rows:
            if row["fixture"] != fixture or not row["ok"]:
                continue
            add(
                f"| `{fixture}` | `{row['backend']}` | {row['tokens_before']:,} | "
                f"{row['tokens_after']:,} | {_fmt_change(row)} | {_fmt_fidelity(row)} |"
            )
    add("")

    # --- Table 2: PDFs, cost against fidelity ------------------------------
    add("## Table 2 — PDF: what the cheapest output cost")
    add("")
    add("| Document | Backend | Bytes out | Fidelity | Median | Added RSS |")
    add("|---|---|---|---|---|---|")
    for fixture in _PDF_ORDER:
        cells = [r for r in rows if r["fixture"] == fixture and r["ok"]]
        for row in sorted(cells, key=lambda r: r["fidelity"] or 0):
            median = _median_ms(row)
            added = row.get("added_rss_kb")
            add(
                f"| `{fixture}` | `{row['backend']}` | {row['tokens_after']:,} | "
                f"{_fmt_fidelity(row)} | "
                f"{median:,.0f} ms | "
                f"{'n/a' if added is None else f'{added / 1024:,.0f} MiB'} |"
            )
    add("")

    # --- Table 3: the cells that succeed and mean nothing -------------------
    add("## Table 3 — Four successes that extracted nothing")
    add("")
    add("`scanned.pdf` has no text layer. These cells return successfully with an")
    add("empty string, which scores a perfect reduction.")
    add("")
    add("| Document | Backend | Reduction | Fidelity | Verdict |")
    add("|---|---|---|---|---|")
    for row in rows:
        if row["fixture"] != "scanned.pdf":
            continue
        if row["ok"] and row["empty_output"]:
            add(
                f"| `scanned.pdf` | `{row['backend']}` | 100% | "
                f"{_fmt_fidelity(row)} | succeeded, extracted nothing |"
            )
    for row in rows:
        if row["fixture"] == "scanned.pdf" and not row["ok"]:
            add(
                f"| `scanned.pdf` | `{row['backend']}` | n/a | n/a | "
                f"**failed, and said to try OCR** |"
            )
    add("")

    # --- Table 4: what a process boundary costs ----------------------------
    add("## Table 4 — What running a converter out of process costs")
    add("")
    add("`Added RSS` is the peak resident set of this process **and its")
    add("descendants** during the cell, minus a reading taken immediately before")
    add("it. Sampled every 5 ms, so it is a lower bound.")
    add("")
    add("| Backend | Runs as | Added RSS across its cells |")
    add("|---|---|---|")
    for backend, description in (
        ("pandoc", "a separate program"),
        ("libreoffice", "a separate program"),
        ("repomix", "`npx` &rarr; `node`"),
        ("pymupdf4llm", "a separate Python interpreter (AGPL, never imported)"),
        ("kreuzberg", "in-process Python"),
        ("trafilatura", "in-process Python"),
    ):
        values = sorted(
            {
                round((r["added_rss_kb"] or 0) / 1024)
                for r in rows
                if r["backend"] == backend and r["ok"] and r.get("added_rss_kb") is not None
            }
        )
        rendered = ", ".join(f"{v}" for v in values) + " MiB" if values else "n/a"
        add(f"| `{backend}` | {description} | {rendered} |")
    add("")

    # --- Table 5: repository packing ---------------------------------------
    add("## Table 5 — Packing a repository")
    add("")
    add("| Engine | Bytes out | Fidelity | Median | Added RSS |")
    add("|---|---|---|---|---|")
    for backend in ("gitingest", "repomix"):
        packed = by_key.get(("sample_repo", backend))
        if packed is None or not packed["ok"]:
            continue
        row = packed
        added = row.get("added_rss_kb")
        add(
            f"| `{backend}` | {row['tokens_after']:,} | {_fmt_fidelity(row)} | "
            f"{_median_ms(row):,.0f} ms | "
            f"{'n/a' if added is None else f'{added / 1024:,.0f} MiB'} |"
        )
    add("")
    add("No before-count: nobody hands a model the raw bytes of a directory, so")
    add("there is nothing to subtract from. The honest figure is what the pack")
    add("costs.")
    add("")

    # --- Table 6: conversion is not always a saving ------------------------
    add("## Table 6 — When converting costs more than it saves")
    add("")
    add("Input that is already Markdown. There is nothing to strip, so the only")
    add("thing a converter can do is change the syntax — and one of them makes it")
    add("**larger**. This is the least flattering cell in the corpus and it is")
    add("here for that reason.")
    add("")
    add("| Input | Backend | Before | After | Change | Fidelity |")
    add("|---|---|---|---|---|---|")
    for fixture in ("structured.md", "long_context.md"):
        for row in rows:
            if row["fixture"] != fixture or not row["ok"]:
                continue
            add(
                f"| `{fixture}` | `{row['backend']}` | {row['tokens_before']:,} | "
                f"{row['tokens_after']:,} | {_fmt_change(row)} | {_fmt_fidelity(row)} |"
            )
    add("")
    add("`pandoc` re-emits `structured.md` **9.5% larger** at a slightly lower")
    add("fidelity: it normalises the Markdown into its own dialect, which is")
    add("more verbose than what was there. `plaintext` passes it through and")
    add("saves 0.2% — three bytes of trailing whitespace.")
    add("")
    add("`long_context.md` is unchanged by both, to the byte. A conversion")
    add("pipeline that reports a saving on input it did not change would be")
    add("broken, and this row is what proves it is not.")
    add("")

    return "\n".join(out) + "\n"


def main(argv: Sequence[str] | None = None) -> int:
    """Write the tables.

    Args:
        argv: Command-line arguments.

    Returns:
        The exit status.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run", type=Path, default=DEFAULT_RUN)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args(argv)

    rows, manifest = _rows(args.run)
    args.out.write_text(render(rows, manifest), encoding="utf-8")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
